version: '3.7'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - '.:/app'

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        volumes:
            - './public/:/app/public:ro'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 80:80
